class payloadConstant{

   dadosGerais = {
     ID_PAYLOAD_FORMAT_INDICATOR : '00',
     ID_POINT_OF_INITIATION_METHOD : '01',
     ID_MERCHANT_ACCOUNT_INFORMATION : '26',
     ID_MERCHANT_ACCOUNT_INFORMATION_GUI : '00',
     ID_MERCHANT_ACCOUNT_INFORMATION_KEY : '01',
     ID_MERCHANT_ACCOUNT_INFORMATION_DESCRIPTION : '02',
     ID_MERCHANT_ACCOUNT_INFORMATION_URL : '25',
     ID_MERCHANT_CATEGORY_CODE : '52',
     ID_TRANSACTION_CURRENCY : '53',
     ID_TRANSACTION_AMOUNT : '54',
     ID_COUNTRY_CODE : '58',
     ID_MERCHANT_NAME : '59',
     ID_MERCHANT_CITY : '60',
     ID_ADDITIONAL_DATA_FIELD_TEMPLATE : '62',
     ID_ADDITIONAL_DATA_FIELD_TEMPLATE_TXID : '05',
     ID_CRC16 : '63'
    }


}

module.exports = payloadConstant